server:
  address: localhost
  port: 8080
  ssl:
    enabled: false
spring:
  application:
    name: api-do-zero
  datasource:
    url: jdbc:h2:mem:naruto;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  sql:
    init:
      mode: always       # executa schema.sql e data.sql no startup
      platform: h2       # habilita sufixos -h2 se quiser
  jpa:
    hibernate:
      ddl-auto: none     # não deixe o Hibernate criar/alterar tabelas
    database-platform: org.hibernate.dialect.H2Dialect

